-- Demo only: real state legislation (verified via web research) replaces
-- NYC bills that had been simulated into other states. Guarded.
do $$ begin
  if to_regclass('public.simulated_environment') is null then
    raise exception 'refusing: not the simulated environment';
  end if;
end $$;

drop table if exists public.demo_state_bills;
create table public.demo_state_bills (st text, id text, title text);

insert into public.bills (id, title, plain_summary, sponsor, chamber, status, topic_category, agree_direction)
values
('hi-sb-1396','SB 1396: Green fee raising hotel tax to fund climate and environment programs','Green fee raising hotel tax to fund climate and environment programs. Real 2025 HI legislation.','Statehouse sponsors','HI Legislature','passed','Climate and environment','yea'),
('hi-hb-1483','HB 1483: Tougher penalties for illegal fireworks offenses','Tougher penalties for illegal fireworks offenses. Real 2025 HI legislation.','Statehouse sponsors','HI Legislature','passed','Public safety','yea'),
('hi-hb-300','HB 300: Two-year state budget of nearly $40 billion','Two-year state budget of nearly $40 billion. Real 2025 HI legislation.','Statehouse sponsors','HI Legislature','passed','Economy','yea'),
('id-hb-345','HB 345: Medicaid reform with work requirements and cost containment','Medicaid reform with work requirements and cost containment. Real 2025 ID legislation.','Statehouse sponsors','ID Legislature','passed','Healthcare','yea'),
('id-hb-93','HB 93: Education tax credits for private school choice','Education tax credits for private school choice. Real 2025 ID legislation.','Statehouse sponsors','ID Legislature','passed','Education','yea'),
('id-sb-1198','SB 1198: Bans DEI programs at state-funded colleges','Bans DEI programs at state-funded colleges. Real 2025 ID legislation.','Statehouse sponsors','ID Legislature','passed','Education','yea'),
('il-hb-1697','HB 1697: Prescription Drug Affordability Act regulating pharmacy benefit managers','Prescription Drug Affordability Act regulating pharmacy benefit managers. Real 2025 IL legislation.','Statehouse sponsors','IL Legislature','passed','Healthcare','yea'),
('il-hb-2755','HB 2755: FY2026 state budget of $55 billion','FY2026 state budget of $55 billion. Real 2025 IL legislation.','Statehouse sponsors','IL Legislature','passed','Economy','yea'),
('il-hb-1859','HB 1859: Bars community colleges from using AI in place of instructors','Bars community colleges from using AI in place of instructors. Real 2025 IL legislation.','Statehouse sponsors','IL Legislature','passed','Technology','yea'),
('in-sb-1','SB 1: Property tax relief with homeowner credits up to $300','Property tax relief with homeowner credits up to $300. Real 2025 IN legislation.','Statehouse sponsors','IN Legislature','passed','Economy','yea'),
('in-sb-143','SB 143: Parental rights limits on schools and state agencies','Parental rights limits on schools and state agencies. Real 2025 IN legislation.','Statehouse sponsors','IN Legislature','passed','Education','yea'),
('in-hb-1001','HB 1001: Two-year state budget','Two-year state budget. Real 2025 IN legislation.','Statehouse sponsors','IN Legislature','passed','Economy','yea'),
('ia-sf-418','SF 418: Removes gender identity protections from state civil rights act','Removes gender identity protections from state civil rights act. Real 2025 IA legislation.','Statehouse sponsors','IA Legislature','passed','Economy','yea'),
('ia-hf-782','HF 782: Restricts student cellphone use during class time','Restricts student cellphone use during class time. Real 2025 IA legislation.','Statehouse sponsors','IA Legislature','passed','Education','yea'),
('ia-hf-639','HF 639: Limits eminent domain for carbon capture pipelines','Limits eminent domain for carbon capture pipelines. Real 2025 IA legislation.','Statehouse sponsors','IA Legislature','failed','Climate and environment','yea'),
('ks-sb-63','SB 63: Bans gender-affirming care for minors','Bans gender-affirming care for minors. Real 2025 KS legislation.','Statehouse sponsors','KS Legislature','passed','Healthcare','yea'),
('ks-sb-4','SB 4: Requires mail ballots to arrive by Election Day','Requires mail ballots to arrive by Election Day. Real 2025 KS legislation.','Statehouse sponsors','KS Legislature','passed','Elections','yea'),
('ks-sb-269','SB 269: Phases in a 4 percent flat income tax','Phases in a 4 percent flat income tax. Real 2025 KS legislation.','Statehouse sponsors','KS Legislature','passed','Economy','yea'),
('ky-hb-1','HB 1: Cuts state income tax from 4 to 3.5 percent','Cuts state income tax from 4 to 3.5 percent. Real 2025 KY legislation.','Statehouse sponsors','KY Legislature','passed','Economy','yea'),
('ky-hb-695','HB 695: Medicaid work requirements and oversight board','Medicaid work requirements and oversight board. Real 2025 KY legislation.','Statehouse sponsors','KY Legislature','passed','Healthcare','yea'),
('ky-sb-2','SB 2: Ends hormone therapy for transgender people in state prisons','Ends hormone therapy for transgender people in state prisons. Real 2025 KY legislation.','Statehouse sponsors','KY Legislature','passed','Healthcare','yea'),
('la-hb-148','HB 148: Gives insurance commissioner more power to hold down rates','Gives insurance commissioner more power to hold down rates. Real 2025 LA legislation.','Statehouse sponsors','LA Legislature','passed','Economy','yea'),
('la-hb-434','HB 434: No Pay No Play limits on uninsured motorist damage awards','No Pay No Play limits on uninsured motorist damage awards. Real 2025 LA legislation.','Statehouse sponsors','LA Legislature','passed','Transportation','yea'),
('la-hb-450','HB 450: Requires crash injury proof in auto lawsuits to curb insurance costs','Requires crash injury proof in auto lawsuits to curb insurance costs. Real 2025 LA legislation.','Statehouse sponsors','LA Legislature','passed','Economy','yea'),
('me-ld-1145','LD 1145: Right of first refusal for mobile home park residents','Right of first refusal for mobile home park residents. Real 2025 ME legislation.','Statehouse sponsors','ME Legislature','passed','Housing','yea'),
('me-ld-128','LD 128: Allows up to four dwelling units per lot in permitting','Allows up to four dwelling units per lot in permitting. Real 2025 ME legislation.','Statehouse sponsors','ME Legislature','passed','Housing','yea'),
('me-ld-1728','LD 1728: Makes childcare affordability measures permanent','Makes childcare affordability measures permanent. Real 2025 ME legislation.','Statehouse sponsors','ME Legislature','passed','Economy','yea'),
('md-hb-1035','HB 1035: Next Generation Energy Act boosting in-state power and curbing costs','Next Generation Energy Act boosting in-state power and curbing costs. Real 2025 MD legislation.','Statehouse sponsors','MD Legislature','passed','Climate and environment','yea'),
('md-sb-931','SB 931: Renewable Energy Certainty Act setting solar farm siting standards','Renewable Energy Certainty Act setting solar farm siting standards. Real 2025 MD legislation.','Statehouse sponsors','MD Legislature','passed','Climate and environment','yea'),
('md-hb-350','HB 350: FY2026 state budget of $67 billion closing deficit','FY2026 state budget of $67 billion closing deficit. Real 2025 MD legislation.','Statehouse sponsors','MD Legislature','passed','Economy','yea'),
('nm-sb-3','SB 3: Behavioral Health Reform and Investment Act','Behavioral Health Reform and Investment Act. Real 2025 NM legislation.','Statehouse sponsors','NM Legislature','passed','Healthcare','yea'),
('nm-hb-8','HB 8: Public safety omnibus on fentanyl, DWI and criminal competency','Public safety omnibus on fentanyl, DWI and criminal competency. Real 2025 NM legislation.','Statehouse sponsors','NM Legislature','passed','Public safety','yea'),
('nm-sb-1','SB 1: Creates statewide behavioral health trust fund','Creates statewide behavioral health trust fund. Real 2025 NM legislation.','Statehouse sponsors','NM Legislature','passed','Healthcare','yea'),
('ny-s-6953','S 6953: RAISE Act requiring safety protocols for frontier AI models','RAISE Act requiring safety protocols for frontier AI models. Real 2025 NY legislation.','Statehouse sponsors','NY Legislature','passed','Technology','yea'),
('ny-s-7882','S 7882: Bans algorithm-enabled rent price fixing by landlords','Bans algorithm-enabled rent price fixing by landlords. Real 2025 NY legislation.','Statehouse sponsors','NY Legislature','passed','Housing','yea'),
('ny-s-138','S 138: Medical Aid in Dying Act for terminally ill patients','Medical Aid in Dying Act for terminally ill patients. Real 2025 NY legislation.','Statehouse sponsors','NY Legislature','passed','Healthcare','yea'),
('nc-sb-50','SB 50: Allows permitless concealed carry of handguns for adults 18 and up','Allows permitless concealed carry of handguns for adults 18 and up. Real 2025 NC legislation.','Statehouse sponsors','NC Legislature','passed','Public safety','yea'),
('nc-sb-153','SB 153: Requires cooperation with federal immigration enforcement, bans sanctuaries','Requires cooperation with federal immigration enforcement, bans sanctuaries. Real 2025 NC legislation.','Statehouse sponsors','NC Legislature','passed','Immigration','yea'),
('nc-sb-266','SB 266: Repeals interim 2030 carbon emissions reduction mandate for utilities','Repeals interim 2030 carbon emissions reduction mandate for utilities. Real 2025 NC legislation.','Statehouse sponsors','NC Legislature','passed','Climate and environment','yea'),
('nd-hb-1176','HB 1176: Property tax relief with $1,600 primary residence credit and 3% cap','Property tax relief with $1,600 primary residence credit and 3% cap. Real 2025 ND legislation.','Statehouse sponsors','ND Legislature','passed','Economy','yea'),
('nd-hb-1160','HB 1160: Requires bell-to-bell phone-free policies in K-12 schools','Requires bell-to-bell phone-free policies in K-12 schools. Real 2025 ND legislation.','Statehouse sponsors','ND Legislature','passed','Education','yea'),
('nd-sb-2307','SB 2307: Restricting sexually explicit library content for minors, vetoed','Restricting sexually explicit library content for minors, vetoed. Real 2025 ND legislation.','Statehouse sponsors','ND Legislature','failed','Education','yea'),
('oh-sb-1','SB 1: Higher education overhaul banning DEI and faculty strikes','Higher education overhaul banning DEI and faculty strikes. Real 2025 OH legislation.','Statehouse sponsors','OH Legislature','passed','Education','yea'),
('oh-hb-96','HB 96: Two-year budget with flat income tax and Browns stadium funding','Two-year budget with flat income tax and Browns stadium funding. Real 2025 OH legislation.','Statehouse sponsors','OH Legislature','passed','Economy','yea'),
('oh-hb-186','HB 186: Limits property tax hikes from rising home values','Limits property tax hikes from rising home values. Real 2025 OH legislation.','Statehouse sponsors','OH Legislature','passed','Economy','yea'),
('ok-hb-2764','HB 2764: Cuts top income tax rate to 4.5% with path to zero','Cuts top income tax rate to 4.5% with path to zero. Real 2025 OK legislation.','Statehouse sponsors','OK Legislature','passed','Economy','yea'),
('ok-sb-139','SB 139: Bans student cell phone use during school day','Bans student cell phone use during school day. Real 2025 OK legislation.','Statehouse sponsors','OK Legislature','passed','Education','yea'),
('ok-hb-4156','HB 4156: Makes illegal presence in state a crime of impermissible occupation','Makes illegal presence in state a crime of impermissible occupation. Real 2024 OK legislation.','Statehouse sponsors','OK Legislature','passed','Immigration','yea'),
('or-sb-916','SB 916: Grants unemployment benefits to striking workers','Grants unemployment benefits to striking workers. Real 2025 OR legislation.','Statehouse sponsors','OR Legislature','passed','Economy','yea'),
('or-hb-2025','HB 2025: Transportation Reinvestment Package to fund roads and transit','Transportation Reinvestment Package to fund roads and transit. Real 2025 OR legislation.','Statehouse sponsors','OR Legislature','failed','Transportation','yea'),
('or-hb-3991','HB 3991: Emergency transportation funding via gas tax and fee increases','Emergency transportation funding via gas tax and fee increases. Real 2025 OR legislation.','Statehouse sponsors','OR Legislature','passed','Transportation','yea'),
('pa-hb-1549','HB 1549: Raises minimum wage to $15 by 2029 with tiered county schedule','Raises minimum wage to $15 by 2029 with tiered county schedule. Real 2025 PA legislation.','Statehouse sponsors','PA Legislature','in_committee','Economy','yea'),
('pa-hb-1200','HB 1200: Legalizes recreational marijuana with state-run stores','Legalizes recreational marijuana with state-run stores. Real 2025 PA legislation.','Statehouse sponsors','PA Legislature','failed','Economy','yea'),
('pa-hb-504','HB 504: Community energy act enabling community solar subscriptions','Community energy act enabling community solar subscriptions. Real 2025 PA legislation.','Statehouse sponsors','PA Legislature','in_committee','Climate and environment','yea'),
('ri-s-359','S 359: Bans manufacture and sale of assault-style weapons','Bans manufacture and sale of assault-style weapons. Real 2025 RI legislation.','Statehouse sponsors','RI Legislature','passed','Public safety','yea'),
('ri-h-5598','H 5598: Requires schools to bar student cell phone access during school day','Requires schools to bar student cell phone access during school day. Real 2025 RI legislation.','Statehouse sponsors','RI Legislature','passed','Education','yea'),
('ri-h-5726','H 5726: Freedom to Read Act prohibiting library book censorship','Freedom to Read Act prohibiting library book censorship. Real 2025 RI legislation.','Statehouse sponsors','RI Legislature','passed','Education','yea'),
('sc-h-3309','H 3309: Energy Security Act expanding power generation to meet demand','Energy Security Act expanding power generation to meet demand. Real 2025 SC legislation.','Statehouse sponsors','SC Legislature','passed','Climate and environment','yea'),
('sc-h-3430','H 3430: Liquor liability and tort reform to lower insurance costs','Liquor liability and tort reform to lower insurance costs. Real 2025 SC legislation.','Statehouse sponsors','SC Legislature','passed','Economy','yea'),
('sc-s-62','S 62: Education Scholarship Trust Fund private school vouchers','Education Scholarship Trust Fund private school vouchers. Real 2025 SC legislation.','Statehouse sponsors','SC Legislature','passed','Education','yea'),
('ma-s-2538','S.2538: Shield Act 2.0 protecting reproductive and gender-affirming care','Shield Act 2.0 protecting reproductive and gender-affirming care. Real 2025 MA legislation.','Statehouse sponsors','MA Legislature','passed','Healthcare','yea'),
('ma-h-4977','H.4977: Affordable Homes Act, $5.16 billion housing bond and policy package','Affordable Homes Act, $5.16 billion housing bond and policy package. Real 2024 MA legislation.','Statehouse sponsors','MA Legislature','passed','Housing','yea'),
('ma-s-2967','S.2967: Clean energy grid, siting and permitting reform climate law','Clean energy grid, siting and permitting reform climate law. Real 2024 MA legislation.','Statehouse sponsors','MA Legislature','passed','Climate and environment','yea'),
('mi-sb-8','SB 8: Raises minimum wage to $15 and revises tipped wage schedule','Raises minimum wage to $15 and revises tipped wage schedule. Real 2025 MI legislation.','Statehouse sponsors','MI Legislature','passed','Economy','yea'),
('mi-hb-4002','HB 4002: Amends Earned Sick Time Act on paid sick leave requirements','Amends Earned Sick Time Act on paid sick leave requirements. Real 2025 MI legislation.','Statehouse sponsors','MI Legislature','passed','Economy','yea'),
('mi-hb-4180','HB 4180: Road funding package shifting fuel taxes to fix roads','Road funding package shifting fuel taxes to fix roads. Real 2025 MI legislation.','Statehouse sponsors','MI Legislature','passed','Transportation','yea'),
('mn-hf-1','HF 1: Repeals MinnesotaCare coverage for undocumented adults','Repeals MinnesotaCare coverage for undocumented adults. Real 2025 MN legislation.','Statehouse sponsors','MN Legislature','passed','Healthcare','yea'),
('mn-hf-16','HF 16: Regulates hyperscale data centers, energy and water use fees','Regulates hyperscale data centers, energy and water use fees. Real 2025 MN legislation.','Statehouse sponsors','MN Legislature','passed','Technology','yea'),
('mn-sf-3567','SF 3567: Requires school districts to adopt student cell phone policies','Requires school districts to adopt student cell phone policies. Real 2024 MN legislation.','Statehouse sponsors','MN Legislature','passed','Education','yea'),
('ms-hb-1','HB 1: Build Up Mississippi Act phasing out individual income tax','Build Up Mississippi Act phasing out individual income tax. Real 2025 MS legislation.','Statehouse sponsors','MS Legislature','passed','Economy','yea'),
('ms-hb-1193','HB 1193: Bans DEI programs and teachings in public schools and colleges','Bans DEI programs and teachings in public schools and colleges. Real 2025 MS legislation.','Statehouse sponsors','MS Legislature','passed','Education','yea'),
('ms-hb-4130','HB 4130: Mississippi Student Funding Formula replacing MAEP school funding','Mississippi Student Funding Formula replacing MAEP school funding. Real 2024 MS legislation.','Statehouse sponsors','MS Legislature','passed','Education','yea'),
('mo-hb-567','HB 567: Repeals voter-approved paid sick leave and wage indexing','Repeals voter-approved paid sick leave and wage indexing. Real 2025 MO legislation.','Statehouse sponsors','MO Legislature','passed','Economy','yea'),
('mo-hjr-73','HJR 73: Ballot measure to repeal abortion rights amendment and ban most abortions','Ballot measure to repeal abortion rights amendment and ban most abortions. Real 2025 MO legislation.','Statehouse sponsors','MO Legislature','passed','Healthcare','yea'),
('mo-hb-495','HB 495: Public safety bill placing St. Louis police under state control','Public safety bill placing St. Louis police under state control. Real 2025 MO legislation.','Statehouse sponsors','MO Legislature','passed','Public safety','yea'),
('mt-hb-231','HB 231: Property tax relief for primary residences and long-term rentals','Property tax relief for primary residences and long-term rentals. Real 2025 MT legislation.','Statehouse sponsors','MT Legislature','passed','Economy','yea'),
('mt-sb-542','SB 542: Second-home and short-term rental property tax increase','Second-home and short-term rental property tax increase. Real 2025 MT legislation.','Statehouse sponsors','MT Legislature','passed','Economy','yea'),
('mt-hb-245','HB 245: Continues Medicaid expansion by removing program sunset','Continues Medicaid expansion by removing program sunset. Real 2025 MT legislation.','Statehouse sponsors','MT Legislature','passed','Healthcare','yea'),
('ne-lb-140','LB 140: Requires schools to adopt policies limiting cell phone use','Requires schools to adopt policies limiting cell phone use. Real 2025 NE legislation.','Statehouse sponsors','NE Legislature','passed','Education','yea'),
('ne-lb-89','LB 89: Defines sex in state law and restricts school sports by biological sex','Defines sex in state law and restricts school sports by biological sex. Real 2025 NE legislation.','Statehouse sponsors','NE Legislature','passed','Education','yea'),
('ne-lb-383','LB 383: Parental controls and protections for minors on social media','Parental controls and protections for minors on social media. Real 2025 NE legislation.','Statehouse sponsors','NE Legislature','passed','Technology','yea'),
('nv-ab-540','AB 540: Attainable Housing Act funding $130 million for workforce housing','Attainable Housing Act funding $130 million for workforce housing. Real 2025 NV legislation.','Statehouse sponsors','NV Legislature','passed','Housing','yea'),
('nv-ab-555','AB 555: Caps insulin copays at $35 per month under private insurance','Caps insulin copays at $35 per month under private insurance. Real 2025 NV legislation.','Statehouse sponsors','NV Legislature','passed','Healthcare','yea'),
('nv-ab-499','AB 499: Voter ID requirement with expanded mail ballot drop boxes','Voter ID requirement with expanded mail ballot drop boxes. Real 2025 NV legislation.','Statehouse sponsors','NV Legislature','failed','Elections','yea'),
('nh-hb-592','HB 592: Rolls back bail reform and eliminates magistrate system','Rolls back bail reform and eliminates magistrate system. Real 2025 NH legislation.','Statehouse sponsors','NH Legislature','passed','Public safety','yea'),
('nh-sb-295','SB 295: Makes Education Freedom Account school choice program universal','Makes Education Freedom Account school choice program universal. Real 2025 NH legislation.','Statehouse sponsors','NH Legislature','passed','Education','yea'),
('nh-hb-377','HB 377: Restricts gender-affirming medical care for minors','Restricts gender-affirming medical care for minors. Real 2025 NH legislation.','Statehouse sponsors','NH Legislature','passed','Healthcare','yea'),
('nj-a4','A4: Overhauls affordable housing obligations under Mount Laurel Doctrine','Overhauls affordable housing obligations under Mount Laurel Doctrine. Real 2024 NJ legislation.','Statehouse sponsors','NJ Legislature','passed','Housing','yea'),
('nj-a3540','A3540: Civil and criminal penalties for creating and spreading deepfakes','Civil and criminal penalties for creating and spreading deepfakes. Real 2025 NJ legislation.','Statehouse sponsors','NJ Legislature','passed','Technology','yea'),
('nj-s5036','S5036: Safe Communities Act limiting local cooperation with ICE','Safe Communities Act limiting local cooperation with ICE. Real 2026 NJ legislation.','Statehouse sponsors','NJ Legislature','passed','Immigration','yea'),
('sd-hb-1052','HB 1052: Bans eminent domain for carbon dioxide pipelines','Bans eminent domain for carbon dioxide pipelines. Real 2025 SD legislation.','Statehouse sponsors','SD Legislature','passed','Climate and environment','yea'),
('sd-sb-216','SB 216: Caps owner-occupied property tax assessment increases at 3 percent','Caps owner-occupied property tax assessment increases at 3 percent. Real 2025 SD legislation.','Statehouse sponsors','SD Legislature','passed','Economy','yea'),
('sd-sb-100','SB 100: Allows concealed carry on college campuses with enhanced permit','Allows concealed carry on college campuses with enhanced permit. Real 2025 SD legislation.','Statehouse sponsors','SD Legislature','passed','Public safety','yea'),
('tn-hb-6004','HB 6004: Education Freedom Act creating universal school vouchers','Education Freedom Act creating universal school vouchers. Real 2025 TN legislation.','Statehouse sponsors','TN Legislature','passed','Education','yea'),
('tn-sb-6002','SB 6002: Creates state immigration enforcement division, sanctuary policy penalties','Creates state immigration enforcement division, sanctuary policy penalties. Real 2025 TN legislation.','Statehouse sponsors','TN Legislature','passed','Immigration','yea'),
('tn-hb-2091','HB 2091: ELVIS Act protecting voice and likeness from AI impersonation','ELVIS Act protecting voice and likeness from AI impersonation. Real 2024 TN legislation.','Statehouse sponsors','TN Legislature','passed','Technology','yea'),
('tx-hb-149','HB 149: Texas Responsible AI Governance Act regulating artificial intelligence','Texas Responsible AI Governance Act regulating artificial intelligence. Real 2025 TX legislation.','Statehouse sponsors','TX Legislature','passed','Technology','yea'),
('tx-sb-2','SB 2: Creates education savings account private school voucher program','Creates education savings account private school voucher program. Real 2025 TX legislation.','Statehouse sponsors','TX Legislature','passed','Education','yea'),
('tx-sb-10','SB 10: Requires Ten Commandments displays in public school classrooms','Requires Ten Commandments displays in public school classrooms. Real 2025 TX legislation.','Statehouse sponsors','TX Legislature','passed','Education','yea'),
('ut-sb-142','SB 142: App Store Accountability Act requiring app store age verification','App Store Accountability Act requiring app store age verification. Real 2025 UT legislation.','Statehouse sponsors','UT Legislature','passed','Technology','yea'),
('ut-hb-267','HB 267: Bans collective bargaining for public sector unions','Bans collective bargaining for public sector unions. Real 2025 UT legislation.','Statehouse sponsors','UT Legislature','passed','Economy','yea'),
('ut-hb-77','HB 77: Bans unauthorized flags, including pride flags, in schools and government','Bans unauthorized flags, including pride flags, in schools and government. Real 2025 UT legislation.','Statehouse sponsors','UT Legislature','passed','Education','yea'),
('vt-h-454','H.454: Education reform with foundation funding formula and district consolidation','Education reform with foundation funding formula and district consolidation. Real 2025 VT legislation.','Statehouse sponsors','VT Legislature','passed','Education','yea'),
('vt-s-259','S.259: Climate Superfund Act making fossil fuel companies pay climate damages','Climate Superfund Act making fossil fuel companies pay climate damages. Real 2024 VT legislation.','Statehouse sponsors','VT Legislature','passed','Climate and environment','yea'),
('vt-s-127','S.127: Housing package creating Community and Housing Infrastructure Program','Housing package creating Community and Housing Infrastructure Program. Real 2025 VT legislation.','Statehouse sponsors','VT Legislature','passed','Housing','yea'),
('va-hb-2094','HB 2094: High-Risk Artificial Intelligence Developer and Deployer Act','High-Risk Artificial Intelligence Developer and Deployer Act. Real 2025 VA legislation.','Statehouse sponsors','VA Legislature','failed','Technology','yea'),
('va-sb-854','SB 854: Limits minors under 16 to one hour daily on social media','Limits minors under 16 to one hour daily on social media. Real 2025 VA legislation.','Statehouse sponsors','VA Legislature','passed','Technology','yea'),
('va-sb-738','SB 738: Requires bell to bell cell phone free policies in public schools','Requires bell to bell cell phone free policies in public schools. Real 2025 VA legislation.','Statehouse sponsors','VA Legislature','passed','Education','yea'),
('wa-hb-1163','HB 1163: Requires permit and safety training to purchase firearms','Requires permit and safety training to purchase firearms. Real 2025 WA legislation.','Statehouse sponsors','WA Legislature','passed','Public safety','yea'),
('wa-hb-1217','HB 1217: Caps annual rent increases statewide','Caps annual rent increases statewide. Real 2025 WA legislation.','Statehouse sponsors','WA Legislature','passed','Housing','yea'),
('wa-sb-5041','SB 5041: Extends unemployment benefits to striking workers','Extends unemployment benefits to striking workers. Real 2025 WA legislation.','Statehouse sponsors','WA Legislature','passed','Economy','yea'),
('wv-hb-2354','HB 2354: Bans seven artificial food dyes and additives in foods','Bans seven artificial food dyes and additives in foods. Real 2025 WV legislation.','Statehouse sponsors','WV Legislature','passed','Healthcare','yea'),
('wv-sb-456','SB 456: Riley Gaines Act defining male and female in state law','Riley Gaines Act defining male and female in state law. Real 2025 WV legislation.','Statehouse sponsors','WV Legislature','passed','Public safety','yea'),
('wv-hb-2014','HB 2014: Power Generation Act promoting microgrids for data centers','Power Generation Act promoting microgrids for data centers. Real 2025 WV legislation.','Statehouse sponsors','WV Legislature','passed','Economy','yea'),
('wi-sb-45','SB 45: Two-year state budget with tax cuts and education funding','Two-year state budget with tax cuts and education funding. Real 2025 WI legislation.','Statehouse sponsors','WI Legislature','passed','Economy','yea'),
('wi-sb-106','SB 106: Authorizes psychiatric residential treatment facilities for youth','Authorizes psychiatric residential treatment facilities for youth. Real 2025 WI legislation.','Statehouse sponsors','WI Legislature','passed','Healthcare','yea'),
('wi-sb-124','SB 124: Creates Nuclear Power Summit Board to advance nuclear energy','Creates Nuclear Power Summit Board to advance nuclear energy. Real 2025 WI legislation.','Statehouse sponsors','WI Legislature','passed','Climate and environment','yea'),
('wy-hb-172','HB 172: Repeals gun free zones in schools and government meetings','Repeals gun free zones in schools and government meetings. Real 2025 WY legislation.','Statehouse sponsors','WY Legislature','passed','Public safety','yea'),
('wy-sf-69','SF 69: 25 percent homeowner property tax exemption','25 percent homeowner property tax exemption. Real 2025 WY legislation.','Statehouse sponsors','WY Legislature','passed','Economy','yea'),
('wy-hb-42','HB 42: Requires abortion clinics to be licensed as surgical centers','Requires abortion clinics to be licensed as surgical centers. Real 2025 WY legislation.','Statehouse sponsors','WY Legislature','passed','Healthcare','yea'),
('dc-b26-0164','B26-0164: RENTAL Act overhauling eviction and rental housing rules','RENTAL Act overhauling eviction and rental housing rules. Real 2025 DC legislation.','Statehouse sponsors','DC Council','passed','Housing','yea'),
('dc-b25-0345','B25-0345: Secure DC Omnibus crime and public safety measures','Secure DC Omnibus crime and public safety measures. Real 2024 DC legislation.','Statehouse sponsors','DC Council','passed','Public safety','yea'),
('dc-b26-0288','B26-0288: RFK Campus Redevelopment Act approving Commanders stadium deal','RFK Campus Redevelopment Act approving Commanders stadium deal. Real 2025 DC legislation.','Statehouse sponsors','DC Council','passed','Economy','yea'),
('al-hb-166','HB 166: FOCUS Act banning student cell phones in public schools','FOCUS Act banning student cell phones in public schools. Real 2025 AL legislation.','Statehouse sponsors','AL Legislature','passed','Education','yea'),
('al-sb-116','SB 116: State ban on Glock switch machine gun conversion devices','State ban on Glock switch machine gun conversion devices. Real 2025 AL legislation.','Statehouse sponsors','AL Legislature','passed','Public safety','yea'),
('al-sb-79','SB 79: What is a Woman Act defining sex as male or female in state law','What is a Woman Act defining sex as male or female in state law. Real 2025 AL legislation.','Statehouse sponsors','AL Legislature','passed','Healthcare','yea'),
('ak-hb-57','HB 57: School funding boost adding $700 to the Base Student Allocation','School funding boost adding $700 to the Base Student Allocation. Real 2025 AK legislation.','Statehouse sponsors','AK Legislature','passed','Education','yea'),
('ak-sb-39','SB 39: Cap on payday loan interest rates at 36 percent','Cap on payday loan interest rates at 36 percent. Real 2025 AK legislation.','Statehouse sponsors','AK Legislature','failed','Economy','yea'),
('ak-hb-78','HB 78: Restores defined benefit pensions for public employees and teachers','Restores defined benefit pensions for public employees and teachers. Real 2026 AK legislation.','Statehouse sponsors','AK Legislature','passed','Economy','yea'),
('az-sb-1543','SB 1543: Axon bill letting HQ project with apartments skip Scottsdale public vote','Axon bill letting HQ project with apartments skip Scottsdale public vote. Real 2025 AZ legislation.','Statehouse sponsors','AZ Legislature','passed','Housing','yea'),
('az-hb-2281','HB 2281: Emily''s Law creating Turquoise Alert for missing Indigenous people','Emily''s Law creating Turquoise Alert for missing Indigenous people. Real 2025 AZ legislation.','Statehouse sponsors','AZ Legislature','passed','Public safety','yea'),
('az-hb-2112','HB 2112: Age verification requirement for online pornography sites','Age verification requirement for online pornography sites. Real 2025 AZ legislation.','Statehouse sponsors','AZ Legislature','passed','Technology','yea'),
('ar-sb-142','SB 142: Bell to Bell No Cell Act banning phones during the school day','Bell to Bell No Cell Act banning phones during the school day. Real 2025 AR legislation.','Statehouse sponsors','AR Legislature','passed','Education','yea'),
('ar-hb-1150','HB 1150: Bans pharmacy benefit managers from owning pharmacies','Bans pharmacy benefit managers from owning pharmacies. Real 2025 AR legislation.','Statehouse sponsors','AR Legislature','passed','Healthcare','yea'),
('ar-sb-246','SB 246: Arkansas ACCESS Act overhauling higher education and scholarships','Arkansas ACCESS Act overhauling higher education and scholarships. Real 2025 AR legislation.','Statehouse sponsors','AR Legislature','passed','Education','yea'),
('ca-sb-53','SB 53: Transparency in Frontier AI Act regulating advanced AI developers','Transparency in Frontier AI Act regulating advanced AI developers. Real 2025 CA legislation.','Statehouse sponsors','CA Legislature','passed','Technology','yea'),
('ca-sb-79','SB 79: Allows taller apartment buildings near major transit stops','Allows taller apartment buildings near major transit stops. Real 2025 CA legislation.','Statehouse sponsors','CA Legislature','passed','Housing','yea'),
('ca-ab-130','AB 130: CEQA exemption streamlining approval of infill housing projects','CEQA exemption streamlining approval of infill housing projects. Real 2025 CA legislation.','Statehouse sponsors','CA Legislature','passed','Housing','yea'),
('co-sb-25-003','SB 25-003: Requires training course to buy most semiautomatic firearms','Requires training course to buy most semiautomatic firearms. Real 2025 CO legislation.','Statehouse sponsors','CO Legislature','passed','Public safety','yea'),
('co-sb-25-276','SB 25-276: Limits ICE cooperation and protects immigrant data and spaces','Limits ICE cooperation and protects immigrant data and spaces. Real 2025 CO legislation.','Statehouse sponsors','CO Legislature','passed','Immigration','yea'),
('co-sb-24-205','SB 24-205: Colorado AI Act regulating high-risk artificial intelligence systems','Colorado AI Act regulating high-risk artificial intelligence systems. Real 2024 CO legislation.','Statehouse sponsors','CO Legislature','passed','Technology','yea'),
('ct-sb-4','SB 4: Energy affordability law cutting electric rates and utility oversight','Energy affordability law cutting electric rates and utility oversight. Real 2025 CT legislation.','Statehouse sponsors','CT Legislature','passed','Climate and environment','yea'),
('ct-hb-5002','HB 5002: Statewide affordable housing and zoning reform package','Statewide affordable housing and zoning reform package. Real 2025 CT legislation.','Statehouse sponsors','CT Legislature','failed','Housing','yea'),
('ct-sb-5','SB 5: AI regulation with sandbox and social media protections for minors','AI regulation with sandbox and social media protections for minors. Real 2026 CT legislation.','Statehouse sponsors','CT Legislature','passed','Technology','yea'),
('de-sb-21','SB 21: Corporate law overhaul to keep companies like Meta incorporated in Delaware','Corporate law overhaul to keep companies like Meta incorporated in Delaware. Real 2025 DE legislation.','Statehouse sponsors','DE Legislature','passed','Economy','yea'),
('de-hb-140','HB 140: End of Life Options Act allowing medical aid in dying','End of Life Options Act allowing medical aid in dying. Real 2025 DE legislation.','Statehouse sponsors','DE Legislature','passed','Healthcare','yea'),
('de-sb-159','SB 159: Permits offshore wind substation over county objection','Permits offshore wind substation over county objection. Real 2025 DE legislation.','Statehouse sponsors','DE Legislature','passed','Climate and environment','yea'),
('fl-hb-1205','HB 1205: Tighter rules and penalties for citizen ballot initiative petitions','Tighter rules and penalties for citizen ballot initiative petitions. Real 2025 FL legislation.','Statehouse sponsors','FL Legislature','passed','Elections','yea'),
('fl-sb-180','SB 180: Hurricane recovery law blocking stricter local land use rules','Hurricane recovery law blocking stricter local land use rules. Real 2025 FL legislation.','Statehouse sponsors','FL Legislature','passed','Climate and environment','yea'),
('fl-hb-3','HB 3: Bans social media accounts for children under 14','Bans social media accounts for children under 14. Real 2024 FL legislation.','Statehouse sponsors','FL Legislature','passed','Technology','yea'),
('ga-sb-68','SB 68: Tort reform limiting lawsuits and civil damages','Tort reform limiting lawsuits and civil damages. Real 2025 GA legislation.','Statehouse sponsors','GA Legislature','passed','Economy','yea'),
('ga-hb-268','HB 268: School safety law with panic alert technology, Ricky and Alyssa''s Law','School safety law with panic alert technology, Ricky and Alyssa''s Law. Real 2025 GA legislation.','Statehouse sponsors','GA Legislature','passed','Public safety','yea'),
('ga-hb-111','HB 111: Cuts the state income tax rate','Cuts the state income tax rate. Real 2025 GA legislation.','Statehouse sponsors','GA Legislature','passed','Economy','yea')
on conflict (id) do update set title = excluded.title,
  plain_summary = excluded.plain_summary, chamber = excluded.chamber,
  status = excluded.status, topic_category = excluded.topic_category;

insert into public.demo_state_bills (st, id, title) values
('hi','hi-sb-1396','SB 1396: Green fee raising hotel tax to fund climate and environment programs'),
('hi','hi-hb-1483','HB 1483: Tougher penalties for illegal fireworks offenses'),
('hi','hi-hb-300','HB 300: Two-year state budget of nearly $40 billion'),
('id','id-hb-345','HB 345: Medicaid reform with work requirements and cost containment'),
('id','id-hb-93','HB 93: Education tax credits for private school choice'),
('id','id-sb-1198','SB 1198: Bans DEI programs at state-funded colleges'),
('il','il-hb-1697','HB 1697: Prescription Drug Affordability Act regulating pharmacy benefit managers'),
('il','il-hb-2755','HB 2755: FY2026 state budget of $55 billion'),
('il','il-hb-1859','HB 1859: Bars community colleges from using AI in place of instructors'),
('in','in-sb-1','SB 1: Property tax relief with homeowner credits up to $300'),
('in','in-sb-143','SB 143: Parental rights limits on schools and state agencies'),
('in','in-hb-1001','HB 1001: Two-year state budget'),
('ia','ia-sf-418','SF 418: Removes gender identity protections from state civil rights act'),
('ia','ia-hf-782','HF 782: Restricts student cellphone use during class time'),
('ia','ia-hf-639','HF 639: Limits eminent domain for carbon capture pipelines'),
('ks','ks-sb-63','SB 63: Bans gender-affirming care for minors'),
('ks','ks-sb-4','SB 4: Requires mail ballots to arrive by Election Day'),
('ks','ks-sb-269','SB 269: Phases in a 4 percent flat income tax'),
('ky','ky-hb-1','HB 1: Cuts state income tax from 4 to 3.5 percent'),
('ky','ky-hb-695','HB 695: Medicaid work requirements and oversight board'),
('ky','ky-sb-2','SB 2: Ends hormone therapy for transgender people in state prisons'),
('la','la-hb-148','HB 148: Gives insurance commissioner more power to hold down rates'),
('la','la-hb-434','HB 434: No Pay No Play limits on uninsured motorist damage awards'),
('la','la-hb-450','HB 450: Requires crash injury proof in auto lawsuits to curb insurance costs'),
('me','me-ld-1145','LD 1145: Right of first refusal for mobile home park residents'),
('me','me-ld-128','LD 128: Allows up to four dwelling units per lot in permitting'),
('me','me-ld-1728','LD 1728: Makes childcare affordability measures permanent'),
('md','md-hb-1035','HB 1035: Next Generation Energy Act boosting in-state power and curbing costs'),
('md','md-sb-931','SB 931: Renewable Energy Certainty Act setting solar farm siting standards'),
('md','md-hb-350','HB 350: FY2026 state budget of $67 billion closing deficit'),
('nm','nm-sb-3','SB 3: Behavioral Health Reform and Investment Act'),
('nm','nm-hb-8','HB 8: Public safety omnibus on fentanyl, DWI and criminal competency'),
('nm','nm-sb-1','SB 1: Creates statewide behavioral health trust fund'),
('ny','ny-s-6953','S 6953: RAISE Act requiring safety protocols for frontier AI models'),
('ny','ny-s-7882','S 7882: Bans algorithm-enabled rent price fixing by landlords'),
('ny','ny-s-138','S 138: Medical Aid in Dying Act for terminally ill patients'),
('nc','nc-sb-50','SB 50: Allows permitless concealed carry of handguns for adults 18 and up'),
('nc','nc-sb-153','SB 153: Requires cooperation with federal immigration enforcement, bans sanctuaries'),
('nc','nc-sb-266','SB 266: Repeals interim 2030 carbon emissions reduction mandate for utilities'),
('nd','nd-hb-1176','HB 1176: Property tax relief with $1,600 primary residence credit and 3% cap'),
('nd','nd-hb-1160','HB 1160: Requires bell-to-bell phone-free policies in K-12 schools'),
('nd','nd-sb-2307','SB 2307: Restricting sexually explicit library content for minors, vetoed'),
('oh','oh-sb-1','SB 1: Higher education overhaul banning DEI and faculty strikes'),
('oh','oh-hb-96','HB 96: Two-year budget with flat income tax and Browns stadium funding'),
('oh','oh-hb-186','HB 186: Limits property tax hikes from rising home values'),
('ok','ok-hb-2764','HB 2764: Cuts top income tax rate to 4.5% with path to zero'),
('ok','ok-sb-139','SB 139: Bans student cell phone use during school day'),
('ok','ok-hb-4156','HB 4156: Makes illegal presence in state a crime of impermissible occupation'),
('or','or-sb-916','SB 916: Grants unemployment benefits to striking workers'),
('or','or-hb-2025','HB 2025: Transportation Reinvestment Package to fund roads and transit'),
('or','or-hb-3991','HB 3991: Emergency transportation funding via gas tax and fee increases'),
('pa','pa-hb-1549','HB 1549: Raises minimum wage to $15 by 2029 with tiered county schedule'),
('pa','pa-hb-1200','HB 1200: Legalizes recreational marijuana with state-run stores'),
('pa','pa-hb-504','HB 504: Community energy act enabling community solar subscriptions'),
('ri','ri-s-359','S 359: Bans manufacture and sale of assault-style weapons'),
('ri','ri-h-5598','H 5598: Requires schools to bar student cell phone access during school day'),
('ri','ri-h-5726','H 5726: Freedom to Read Act prohibiting library book censorship'),
('sc','sc-h-3309','H 3309: Energy Security Act expanding power generation to meet demand'),
('sc','sc-h-3430','H 3430: Liquor liability and tort reform to lower insurance costs'),
('sc','sc-s-62','S 62: Education Scholarship Trust Fund private school vouchers'),
('ma','ma-s-2538','S.2538: Shield Act 2.0 protecting reproductive and gender-affirming care'),
('ma','ma-h-4977','H.4977: Affordable Homes Act, $5.16 billion housing bond and policy package'),
('ma','ma-s-2967','S.2967: Clean energy grid, siting and permitting reform climate law'),
('mi','mi-sb-8','SB 8: Raises minimum wage to $15 and revises tipped wage schedule'),
('mi','mi-hb-4002','HB 4002: Amends Earned Sick Time Act on paid sick leave requirements'),
('mi','mi-hb-4180','HB 4180: Road funding package shifting fuel taxes to fix roads'),
('mn','mn-hf-1','HF 1: Repeals MinnesotaCare coverage for undocumented adults'),
('mn','mn-hf-16','HF 16: Regulates hyperscale data centers, energy and water use fees'),
('mn','mn-sf-3567','SF 3567: Requires school districts to adopt student cell phone policies'),
('ms','ms-hb-1','HB 1: Build Up Mississippi Act phasing out individual income tax'),
('ms','ms-hb-1193','HB 1193: Bans DEI programs and teachings in public schools and colleges'),
('ms','ms-hb-4130','HB 4130: Mississippi Student Funding Formula replacing MAEP school funding'),
('mo','mo-hb-567','HB 567: Repeals voter-approved paid sick leave and wage indexing'),
('mo','mo-hjr-73','HJR 73: Ballot measure to repeal abortion rights amendment and ban most abortions'),
('mo','mo-hb-495','HB 495: Public safety bill placing St. Louis police under state control'),
('mt','mt-hb-231','HB 231: Property tax relief for primary residences and long-term rentals'),
('mt','mt-sb-542','SB 542: Second-home and short-term rental property tax increase'),
('mt','mt-hb-245','HB 245: Continues Medicaid expansion by removing program sunset'),
('ne','ne-lb-140','LB 140: Requires schools to adopt policies limiting cell phone use'),
('ne','ne-lb-89','LB 89: Defines sex in state law and restricts school sports by biological sex'),
('ne','ne-lb-383','LB 383: Parental controls and protections for minors on social media'),
('nv','nv-ab-540','AB 540: Attainable Housing Act funding $130 million for workforce housing'),
('nv','nv-ab-555','AB 555: Caps insulin copays at $35 per month under private insurance'),
('nv','nv-ab-499','AB 499: Voter ID requirement with expanded mail ballot drop boxes'),
('nh','nh-hb-592','HB 592: Rolls back bail reform and eliminates magistrate system'),
('nh','nh-sb-295','SB 295: Makes Education Freedom Account school choice program universal'),
('nh','nh-hb-377','HB 377: Restricts gender-affirming medical care for minors'),
('nj','nj-a4','A4: Overhauls affordable housing obligations under Mount Laurel Doctrine'),
('nj','nj-a3540','A3540: Civil and criminal penalties for creating and spreading deepfakes'),
('nj','nj-s5036','S5036: Safe Communities Act limiting local cooperation with ICE'),
('sd','sd-hb-1052','HB 1052: Bans eminent domain for carbon dioxide pipelines'),
('sd','sd-sb-216','SB 216: Caps owner-occupied property tax assessment increases at 3 percent'),
('sd','sd-sb-100','SB 100: Allows concealed carry on college campuses with enhanced permit'),
('tn','tn-hb-6004','HB 6004: Education Freedom Act creating universal school vouchers'),
('tn','tn-sb-6002','SB 6002: Creates state immigration enforcement division, sanctuary policy penalties'),
('tn','tn-hb-2091','HB 2091: ELVIS Act protecting voice and likeness from AI impersonation'),
('tx','tx-hb-149','HB 149: Texas Responsible AI Governance Act regulating artificial intelligence'),
('tx','tx-sb-2','SB 2: Creates education savings account private school voucher program'),
('tx','tx-sb-10','SB 10: Requires Ten Commandments displays in public school classrooms'),
('ut','ut-sb-142','SB 142: App Store Accountability Act requiring app store age verification'),
('ut','ut-hb-267','HB 267: Bans collective bargaining for public sector unions'),
('ut','ut-hb-77','HB 77: Bans unauthorized flags, including pride flags, in schools and government'),
('vt','vt-h-454','H.454: Education reform with foundation funding formula and district consolidation'),
('vt','vt-s-259','S.259: Climate Superfund Act making fossil fuel companies pay climate damages'),
('vt','vt-s-127','S.127: Housing package creating Community and Housing Infrastructure Program'),
('va','va-hb-2094','HB 2094: High-Risk Artificial Intelligence Developer and Deployer Act'),
('va','va-sb-854','SB 854: Limits minors under 16 to one hour daily on social media'),
('va','va-sb-738','SB 738: Requires bell to bell cell phone free policies in public schools'),
('wa','wa-hb-1163','HB 1163: Requires permit and safety training to purchase firearms'),
('wa','wa-hb-1217','HB 1217: Caps annual rent increases statewide'),
('wa','wa-sb-5041','SB 5041: Extends unemployment benefits to striking workers'),
('wv','wv-hb-2354','HB 2354: Bans seven artificial food dyes and additives in foods'),
('wv','wv-sb-456','SB 456: Riley Gaines Act defining male and female in state law'),
('wv','wv-hb-2014','HB 2014: Power Generation Act promoting microgrids for data centers'),
('wi','wi-sb-45','SB 45: Two-year state budget with tax cuts and education funding'),
('wi','wi-sb-106','SB 106: Authorizes psychiatric residential treatment facilities for youth'),
('wi','wi-sb-124','SB 124: Creates Nuclear Power Summit Board to advance nuclear energy'),
('wy','wy-hb-172','HB 172: Repeals gun free zones in schools and government meetings'),
('wy','wy-sf-69','SF 69: 25 percent homeowner property tax exemption'),
('wy','wy-hb-42','HB 42: Requires abortion clinics to be licensed as surgical centers'),
('dc','dc-b26-0164','B26-0164: RENTAL Act overhauling eviction and rental housing rules'),
('dc','dc-b25-0345','B25-0345: Secure DC Omnibus crime and public safety measures'),
('dc','dc-b26-0288','B26-0288: RFK Campus Redevelopment Act approving Commanders stadium deal'),
('al','al-hb-166','HB 166: FOCUS Act banning student cell phones in public schools'),
('al','al-sb-116','SB 116: State ban on Glock switch machine gun conversion devices'),
('al','al-sb-79','SB 79: What is a Woman Act defining sex as male or female in state law'),
('ak','ak-hb-57','HB 57: School funding boost adding $700 to the Base Student Allocation'),
('ak','ak-sb-39','SB 39: Cap on payday loan interest rates at 36 percent'),
('ak','ak-hb-78','HB 78: Restores defined benefit pensions for public employees and teachers'),
('az','az-sb-1543','SB 1543: Axon bill letting HQ project with apartments skip Scottsdale public vote'),
('az','az-hb-2281','HB 2281: Emily''s Law creating Turquoise Alert for missing Indigenous people'),
('az','az-hb-2112','HB 2112: Age verification requirement for online pornography sites'),
('ar','ar-sb-142','SB 142: Bell to Bell No Cell Act banning phones during the school day'),
('ar','ar-hb-1150','HB 1150: Bans pharmacy benefit managers from owning pharmacies'),
('ar','ar-sb-246','SB 246: Arkansas ACCESS Act overhauling higher education and scholarships'),
('ca','ca-sb-53','SB 53: Transparency in Frontier AI Act regulating advanced AI developers'),
('ca','ca-sb-79','SB 79: Allows taller apartment buildings near major transit stops'),
('ca','ca-ab-130','AB 130: CEQA exemption streamlining approval of infill housing projects'),
('co','co-sb-25-003','SB 25-003: Requires training course to buy most semiautomatic firearms'),
('co','co-sb-25-276','SB 25-276: Limits ICE cooperation and protects immigrant data and spaces'),
('co','co-sb-24-205','SB 24-205: Colorado AI Act regulating high-risk artificial intelligence systems'),
('ct','ct-sb-4','SB 4: Energy affordability law cutting electric rates and utility oversight'),
('ct','ct-hb-5002','HB 5002: Statewide affordable housing and zoning reform package'),
('ct','ct-sb-5','SB 5: AI regulation with sandbox and social media protections for minors'),
('de','de-sb-21','SB 21: Corporate law overhaul to keep companies like Meta incorporated in Delaware'),
('de','de-hb-140','HB 140: End of Life Options Act allowing medical aid in dying'),
('de','de-sb-159','SB 159: Permits offshore wind substation over county objection'),
('fl','fl-hb-1205','HB 1205: Tighter rules and penalties for citizen ballot initiative petitions'),
('fl','fl-sb-180','SB 180: Hurricane recovery law blocking stricter local land use rules'),
('fl','fl-hb-3','HB 3: Bans social media accounts for children under 14'),
('ga','ga-sb-68','SB 68: Tort reform limiting lawsuits and civil damages'),
('ga','ga-hb-268','HB 268: School safety law with panic alert technology, Ricky and Alyssa''s Law'),
('ga','ga-hb-111','HB 111: Cuts the state income tax rate');


-- Reassign simulated state responses from NYC bills to that state's own
-- bills: each voter keeps at most one rating per state bill, extras drop.
with cand as (
  select w.user_id, w.item_id, split_part(w.district_id, '-', 1) as st,
         row_number() over (partition by w.user_id order by w.item_id) - 1 as rn
  from public.weigh_ins w
  where w.kind = 'bill'
    and split_part(w.district_id, '-', 1) not in ('nyc', 'us')
    and w.item_id like 'nyc-%'
),
b as (
  select st, id, title,
         row_number() over (partition by st order by id) - 1 as rn,
         count(*) over (partition by st) as cnt
  from public.demo_state_bills
)
delete from public.weigh_ins w
using cand c
left join b on b.st = c.st and b.rn = c.rn
where w.user_id = c.user_id and w.kind = 'bill' and w.item_id = c.item_id
  and b.id is null;

with cand as (
  select w.user_id, w.item_id, split_part(w.district_id, '-', 1) as st,
         row_number() over (partition by w.user_id order by w.item_id) - 1 as rn
  from public.weigh_ins w
  where w.kind = 'bill'
    and split_part(w.district_id, '-', 1) not in ('nyc', 'us')
    and w.item_id like 'nyc-%'
),
b as (
  select st, id, title,
         row_number() over (partition by st order by id) - 1 as rn,
         count(*) over (partition by st) as cnt
  from public.demo_state_bills
)
update public.weigh_ins w
set item_id = b.id, title = b.title
from cand c
join b on b.st = c.st and b.rn = c.rn
where w.user_id = c.user_id and w.kind = 'bill' and w.item_id = c.item_id;
