// One time generator: converts the census us-atlas topology into static SVG
// path data (Albers USA projection, 975x610 viewBox) committed to the repo.
import { readFileSync, writeFileSync } from "node:fs";
import * as topojson from "topojson-client";
import { geoAlbersUsa, geoPath } from "d3-geo";

const FIPS = {
  "01":"AL","02":"AK","04":"AZ","05":"AR","06":"CA","08":"CO","09":"CT","10":"DE",
  "11":"DC","12":"FL","13":"GA","15":"HI","16":"ID","17":"IL","18":"IN","19":"IA",
  "20":"KS","21":"KY","22":"LA","23":"ME","24":"MD","25":"MA","26":"MI","27":"MN",
  "28":"MS","29":"MO","30":"MT","31":"NE","32":"NV","33":"NH","34":"NJ","35":"NM",
  "36":"NY","37":"NC","38":"ND","39":"OH","40":"OK","41":"OR","42":"PA","44":"RI",
  "45":"SC","46":"SD","47":"TN","48":"TX","49":"UT","50":"VT","51":"VA","53":"WA",
  "54":"WV","55":"WI","56":"WY",
};

const topo = JSON.parse(readFileSync("node_modules/us-atlas/states-10m.json", "utf8"));
const states = topojson.feature(topo, topo.objects.states).features;
const projection = geoAlbersUsa().scale(1300).translate([487.5, 305]);
const path = geoPath(projection);

const out = states
  .filter((f) => FIPS[f.id])
  .map((f) => {
    const [x0, y0, x1, y1] = path.bounds(f).flat();
    const [cx, cy] = path.centroid(f);
    return {
      abbr: FIPS[f.id],
      name: f.properties.name,
      d: path(f),
      bounds: [x0, y0, x1, y1].map((v) => Math.round(v * 10) / 10),
      centroid: [Math.round(cx * 10) / 10, Math.round(cy * 10) / 10],
    };
  });

writeFileSync(
  "src/lib/usStatesGeo.ts",
  "// Generated by scripts/generate-us-map.mjs from us-atlas states-10m\n" +
  "// (census geometry, Albers USA projection, viewBox 0 0 975 610).\n" +
  "export type StateGeo = { abbr: string; name: string; d: string; bounds: number[]; centroid: number[] };\n" +
  "export const US_STATES: StateGeo[] = " + JSON.stringify(out) + ";\n"
);
console.log("states written:", out.length);
