// Generates src/lib/usCities.ts: the largest US cities with Albers USA
// coordinates and 2023 census population estimates, for zoom scaled map
// labels. Sources: census place gazetteer + SUB-EST2023 totals.
//   GAZ=2023_Gaz_place_national.txt POP=sub-est2023.csv node scripts/generate-cities.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { geoAlbersUsa } from "d3-geo";

const gazLines = readFileSync(process.env.GAZ, "utf8").split("\n");
const gazHeader = gazLines[0].split("\t").map((h) => h.trim());
const gi = (name) => gazHeader.indexOf(name);
const coords = new Map();
for (const line of gazLines.slice(1)) {
  const p = line.split("\t");
  if (p.length < gazHeader.length) continue;
  coords.set(p[gi("GEOID")].trim(), {
    lat: Number(p[gi("INTPTLAT")]),
    lon: Number(p[gi("INTPTLONG")]),
    st: p[gi("USPS")].trim(),
  });
}

// SUMLEV 162: incorporated place
const popLines = readFileSync(process.env.POP, "latin1").split("\n");
const popHeader = popLines[0].split(",");
const pi = (name) => popHeader.indexOf(name);
const cities = [];
const seen = new Set();
for (const line of popLines.slice(1)) {
  const p = line.split(",");
  if (p[pi("SUMLEV")] !== "162") continue;
  const geoid = p[pi("STATE")].padStart(2, "0") + p[pi("PLACE")].padStart(5, "0");
  if (seen.has(geoid)) continue;
  seen.add(geoid);
  const c = coords.get(geoid);
  if (!c) continue;
  const pop = Number(p[pi("POPESTIMATE2023")]);
  if (!pop || pop < 45000) continue;
  const name = p[pi("NAME")]
    .replace(/ (city|town|village|borough|municipality|CDP)( \(balance\))?$/i, "")
    .replace(/ city and borough$/i, "")
    .replace(/^Urban /, "");
  cities.push({ name, st: c.st, lat: c.lat, lon: c.lon, pop });
}

const albers = geoAlbersUsa().scale(1300).translate([487.5, 305]);
const out = [];
for (const c of cities.sort((a, b) => b.pop - a.pop)) {
  const xy = albers([c.lon, c.lat]);
  if (!xy) continue;
  out.push({
    name: c.name,
    st: c.st,
    x: Math.round(xy[0] * 10) / 10,
    y: Math.round(xy[1] * 10) / 10,
    pop: c.pop,
  });
}

writeFileSync(
  "src/lib/usCities.ts",
  "// Generated by scripts/generate-cities.mjs from census gazetteer and\n" +
    "// SUB-EST2023 population estimates. Albers USA space, viewBox 0 0 975 610.\n" +
    "export type CityDot = { name: string; st: string; x: number; y: number; pop: number };\n" +
    "export const US_CITIES: CityDot[] = " +
    JSON.stringify(out) +
    ";\n"
);
console.log("cities:", out.length, "largest:", out[0]?.name, out[0]?.pop);
